// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImfm_MePQ0qacTepdrI1CHKIurvHMZew',
    appId: '1:425210410288:web:66191fea21ec93074084f5',
    messagingSenderId: '425210410288',
    projectId: 'aplikasi-cctv',
    authDomain: 'aplikasi-cctv.firebaseapp.com',
    storageBucket: 'aplikasi-cctv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8tOfk9L_xUlxo8vgphNKn2zZUAaLU8cs',
    appId: '1:425210410288:android:631bf0f58f6697fa4084f5',
    messagingSenderId: '425210410288',
    projectId: 'aplikasi-cctv',
    storageBucket: 'aplikasi-cctv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttJZgRkMCXCGesc2Dl9ng9nUVF5mc8ec',
    appId: '1:425210410288:ios:3713519ab692656d4084f5',
    messagingSenderId: '425210410288',
    projectId: 'aplikasi-cctv',
    storageBucket: 'aplikasi-cctv.appspot.com',
    iosBundleId: 'com.example.aplikasiCctv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttJZgRkMCXCGesc2Dl9ng9nUVF5mc8ec',
    appId: '1:425210410288:ios:46234c44291b26fe4084f5',
    messagingSenderId: '425210410288',
    projectId: 'aplikasi-cctv',
    storageBucket: 'aplikasi-cctv.appspot.com',
    iosBundleId: 'com.example.aplikasiCctv.RunnerTests',
  );
}
